Add ability to load issues
adobe/adobe-changelog-generator pull request #26
Opened 2021-06-22 06:11 UTC by VladimirZaets

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-06-22 20:33 UTC, naydav reviewed
Maybe make sense to add some tests

2021-06-23 15:05 UTC, lenaorobei commented
Please fix failed build.

2021-06-28 22:38 UTC, naydav requested changes

2021-06-28 22:38 UTC, naydav commented on src/filters/index.js
> +            case 'not in': return !_.includes(config.value, value);
Please add `default` block with an error like `not supported condition type`

2021-06-28 22:38 UTC, naydav commented on src/filters/index.js
> +        const conditions = _.isArray(this.config.conditions[0]) ?
This is a very ambiguous logic.
Do we really need this in the new code?

2021-06-28 22:38 UTC, naydav commented on src/filters/index.js
> +class Index implements FilterInterface {
Please add some description about this class to devdocs
Also maybe make sense to add `@private` annotation to internal methods

Now the "contract look:s like:

```
class Index
- getCondition
- execute
- isSatisfyingOrConditions
- isSatisfyingAndConditions
```

2021-06-28 22:38 UTC, naydav commented on src/filters/index.js
> +     * @param config
Please fix all of doc types

2021-06-28 22:38 UTC, naydav commented on src/filters/index.js
> +    /**
Please code style in all places

2021-06-28 22:38 UTC, naydav commented on src/loaders/pr-and-issue.js
> +import type { graphql } from '@octokit/graphql';
Is it correct behavior? 
`import type`

2021-06-28 22:38 UTC, naydav commented on src/loaders/pr-and-issue.js
> +   * @ram githubService
please fix all dockblocks

2021-06-28 22:38 UTC, naydav commented on src/services/filter-registry.js
> +    get(name:string = 'index', config:Object):Function {
It looks like a filter factory but not a registry

2021-06-28 22:38 UTC, naydav commented on src/services/processor-registry.js
> +     * Loads loader by name
Looks like there is some mess in the naming: class is `ProcessorRegistry`, but dockblcok is  `Loads loader by name`, but real behavior is "factory".

2021-06-28 22:39 UTC, naydav commented on src/filters/index.js
> +/*
Please, take a look at dockblocks indent in all files.

2021-06-29 14:12 UTC, lenaorobei commented on src/loaders/issue.js
> +class IssueLoader implements LoaderInterface {
Please add annotations about the purpose of this class and its specific.

2021-06-29 14:13 UTC, lenaorobei commented on src/loaders/issue.js
> +              timelineItems(first: 100 itemTypes: [
Do we need cross references even for the simplest issue loader?

2021-06-29 14:15 UTC, lenaorobei commented on src/loaders/pullrequest.js
> +          author: item.author ? item.author.login : 'ghost',
Do we really need to hardcode 'ghost' here?

2021-06-29 14:16 UTC, lenaorobei commented on src/processors/selected-labels.js
> +                'MagentoComponentLabels config error: required option "componentLabelRegExp" is not provided'
It makes sense to keep this class more general, not tied to Magento. The name of the class doesn't reflect this as well.

2021-06-29 14:18 UTC, lenaorobei commented on src/writers/json-format-magento.js
>                          "end_date": changelogData[namespace][release].to,
I would recommend not using Magento in file names and code. Please change it to Commerce.

2021-06-29 14:19 UTC, lenaorobei commented on src/filters/index.js
> +            case 'is': {
Please add documentation about available conditions.

2021-06-29 14:25 UTC, lenaorobei requested changes
Please cover new functionality with the tests and add documentation.

2021-06-30 03:25 UTC, VladimirZaets commented on src/filters/index.js
> +        const conditions = _.isArray(this.config.conditions[0]) ?
It's needed for config simplification. Discussed in the scope of the meeting.

2021-06-30 03:25 UTC, VladimirZaets commented on src/filters/index.js
> +class Index implements FilterInterface {
Refactored and moved to separate class

2021-06-30 03:26 UTC, VladimirZaets commented on src/loaders/pr-and-issue.js
> +import type { graphql } from '@octokit/graphql';
yes, discussed in scope of the meeting

2021-06-30 03:32 UTC, VladimirZaets commented on src/loaders/issue.js
> +              timelineItems(first: 100 itemTypes: [
In short - yes. Currently, we have only one customer that works with the issue instead of PRs, and they require crossreference event. In the future, it's a good task to make the possibility to generate requests from the parts, based on client needs. It will give more flexibility, improve performance, but for not it's not a problem.

2021-06-30 03:36 UTC, VladimirZaets commented on src/loaders/pullrequest.js
> +          author: item.author ? item.author.login : 'ghost',
I do it to have the same behaviour with Github. In general, it's bad practice, because it should be on the view layer, but for this application view layer is MD template, and I try to avoid additional logic in templates

2021-06-30 19:43 UTC, lenaorobei commented on src/loaders/issue.js
> +class IssueLoader implements LoaderInterface {
What I meant was to add more info about data that is being loaded (includes cross-reference), etc.

2021-06-30 19:44 UTC, lenaorobei commented on src/loaders/issue.js
> +              timelineItems(first: 100 itemTypes: [
Would be nica if class name is reflecting that.

2021-06-30 19:45 UTC, lenaorobei commented on src/loaders/pullrequest.js
> +          author: item.author ? item.author.login : 'ghost',
So, if PR was created by ghost user, it will not be in the response as item.author.login?

2021-06-30 19:47 UTC, lenaorobei commented on src/processors/selected-labels.js
> +                '"selected-labels" processor error: required option "componentLabelRegExp" is not provided'
Is is supposed to be component-specific? Maybe, it makes sense to rename the class in this case.

2021-06-30 21:30 UTC, VladimirZaets commented on src/loaders/pullrequest.js
> +          author: item.author ? item.author.login : 'ghost',
If PR was created by the user that removed his account, his login will not be in item.author.login, but from Github UI we will see this user as ghost

2021-06-30 21:37 UTC, VladimirZaets commented on src/loaders/issue.js
> +              timelineItems(first: 100 itemTypes: [
I don't think that we need it. Now we have only one option, with cross-references, even if you don't need it you will load it and I don't think that we will have another loader for issues. I believe if we will have a request for it we will create mechanism for generation request instead of creating new loader

2021-06-30 21:38 UTC, VladimirZaets commented on src/loaders/issue.js
> +class IssueLoader implements LoaderInterface {
The data that loaded will be represented in DTO

2021-06-30 21:41 UTC, VladimirZaets commented on src/loaders/issue.js
> +class IssueLoader implements LoaderInterface {
we have the task for it

2021-07-01 18:36 UTC, lenaorobei approved these changes

2021-07-01 18:48 UTC, merged